package app

// Controlled-sshd smoke test.
//
// One narrow assertion: the system ssh executable, driven only by
// ordinary SSH config + an SSH alias, executes one public vci JSON
// command on a coordinator root with `orchestrator = "self"`, and the
// response decodes as a Vci envelope.

import (
	"context"
	"encoding/json"
	"testing"
	"time"
)

// TestVciMachinesOverControlledSSHD executes the public
// coordinator command `vci machines` through ordinary system ssh +
// sshd on a loopback port generated by the fixture.
func TestVciMachinesOverControlledSSHD(t *testing.T) {
	fixture := NewSSHFixture(t)
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	if err := fixture.waitForSSHRoundtrip(ctx); err != nil {
		t.Fatalf("controlled SSH: ssh roundtrip failed: %v", err)
	}

	wrapCmd := "PATH=" + fixture.binDir + ":$PATH vci machines"
	stdout, stderr, err := fixture.ExecSSHCommand(ctx, wrapCmd)
	if err != nil {
		t.Fatalf("ssh session exited non-zero: %v\nstdout:\n%s\nstderr:\n%s", err, stdout, stderr)
	}

	var envelope struct {
		SchemaVersion int             `json:"schema_version"`
		OK            bool            `json:"ok"`
		Command       string          `json:"command"`
		Data          json.RawMessage `json:"data"`
	}
	if err := json.Unmarshal(stdout, &envelope); err != nil {
		t.Fatalf("ssh session produced non-JSON stdout (%v):\n%s", err, stdout)
	}
	if envelope.SchemaVersion != 1 {
		t.Fatalf("unexpected schema_version %d in stdout:\n%s", envelope.SchemaVersion, stdout)
	}
	if envelope.Command != "machines" {
		t.Fatalf("expected command=machines, got %q in stdout:\n%s", envelope.Command, stdout)
	}
	if !envelope.OK {
		t.Fatalf("envelope not ok:\n%s", stdout)
	}
}
